# Development Environment
services:
  backend:
    build:
      context: ./api-express
      dockerfile: Dockerfile
    volumes:
      - ./api-express:/app
    ports:
      - "3210"
    environment:
      - NODE_ENV=development
      - SERVER_PORT=3210
    user: "${UID:-1000}:${GID:-1000}"
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./client-react
      dockerfile: Dockerfile
    volumes:
      - ./client-react:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./api-express/.env
    environment:
      - NODE_ENV=development
      - VITE_SERVER_PORT=5173
      - SERVER_HOST=backend
      - SERVER_PORT=3210
    user: "${UID:-1000}:${GID:-1000}"
    command: ["npm", "run", "dev"]
